<a href="https://colab.research.google.com/github/Integrall11/RNN-pyhthon-implementation/blob/main/Main%20code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.layers import Dense, SimpleRNN
from keras.models import Sequential
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
import math

In [37]:
def create_RNN(hidden_units, dense_units, input_shape, activation):
  model = Sequential()
  model.add(SimpleRNN(units=2, activation=activation[0], input_shape=input_shape))
  model.add(Dense(units=1, activation=activation[1]))
  model.compile(loss='mean_squared_error', optimizer='adam')
  return model

model = create_RNN(2, 1, (3, 1), ['linear', 'linear'])

In [38]:
model.get_weights()

[array([[-0.4600507,  0.8456594]], dtype=float32),
 array([[-0.9963666 , -0.08516783],
        [ 0.08516783, -0.9963666 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.4327554],
        [-0.6919261]], dtype=float32),
 array([0.], dtype=float32)]

In [71]:
X = np.array(range(1, 2001)).reshape(400, 5, 1)
y = np.array([5*x +1 for x in range(1, 401)]).reshape(400, 1)
model.fit(X, y, epochs=40, batch_size=1)

In [72]:
test = np.array(range(3000, 3100)).reshape(20, 5, 1)
model.predict(test)

1/1 [==============================] - 0s 30ms/step


array([[3004.9783],
       [3009.9785],
       [3014.9788],
       [3019.9788],
       [3024.9773],
       [3029.9775],
       [3034.9778],
       [3039.9778],
       [3044.979 ],
       [3049.9773],
       [3054.978 ],
       [3059.9775],
       [3064.9775],
       [3069.9785],
       [3074.9783],
       [3079.9775],
       [3084.977 ],
       [3089.9768],
       [3094.9773],
       [3099.9773]], dtype=float32)

In [70]:
test

array([[[3000],
        [3001],
        [3002],
        [3003],
        [3004]],

       [[3005],
        [3006],
        [3007],
        [3008],
        [3009]],

       [[3010],
        [3011],
        [3012],
        [3013],
        [3014]],

       [[3015],
        [3016],
        [3017],
        [3018],
        [3019]],

       [[3020],
        [3021],
        [3022],
        [3023],
        [3024]],

       [[3025],
        [3026],
        [3027],
        [3028],
        [3029]],

       [[3030],
        [3031],
        [3032],
        [3033],
        [3034]],

       [[3035],
        [3036],
        [3037],
        [3038],
        [3039]],

       [[3040],
        [3041],
        [3042],
        [3043],
        [3044]],

       [[3045],
        [3046],
        [3047],
        [3048],
        [3049]],

       [[3050],
        [3051],
        [3052],
        [3053],
        [3054]],

       [[3055],
        [3056],
        [3057],
        [3058],
        [3059]],

       [[3060],
